export const data = [
  {
    SlNo: 1,
    BookId: 5,
    BookName: "বাংলাদেশের লোকশিল্প",
    BookImg: "1d6aabea-a648-41e1-ac3d-d6ea9d5390d4-image00364.jpg",
    Author: "-",
    Editor: "",
    Category: "লোকশিল্প-বাংলাদেশ",
    YearOfPublished: "1988",
    isPdf: 1,
  },
  {
    SlNo: 2,
    BookId: 7,
    BookName: "লোকসংস্কৃতি",
    BookImg: "d24b2547-1614-4871-b996-7bbb1301bd35-image00001.jpg",
    Author: "মাহমুদ শফিক",
    Editor: "",
    Category: "লোক সংস্কৃতি",
    YearOfPublished: "2005",
    isPdf: 1,
  },
  {
    SlNo: 3,
    BookId: 8,
    BookName: "কারুশিল্পীদের তালিকা",
    BookImg: "1846f9db-a333-428b-91d9-3ca0a7eed6af-image00001.jpg",
    Author: "-",
    Editor: "-",
    Category: "কারুশিল্পী-বাংলাদেশ",
    YearOfPublished: "2005",
    isPdf: 1,
  },
  {
    SlNo: 4,
    BookId: 9,
    BookName: "শিল্পাচার্য জয়নুল আবেদিন",
    BookImg: "7c842499-7960-43a7-878b-1eeab3b9233e-image00012.jpg",
    Author: "-",
    Editor: "-",
    Category: "জীবনী ও কর্ম",
    YearOfPublished: "2006",
    isPdf: 1,
  },
  {
    SlNo: 14,
    BookId: 19,
    BookName: "লোকশিল্প",
    BookImg: "e9a803ba-1d9f-49ea-8269-a8531a571636-image00183.jpg",
    Author: "সৈয়দ মাহবুব আলম",
    Editor: "",
    Category: "লোকশিল্প",
    YearOfPublished: "1999",
    isPdf: 1,
  },
  {
    SlNo: 20,
    BookId: 25,
    BookName: "বাংলাদেশের কারুশিল্পী ও শিল্পকর্ম",
    BookImg: "book-large.jpg",
    Author: "-",
    Editor: "রবীন্দ্র গোপ",
    Category: "বাংলাদেশের কারুশিল্প",
    YearOfPublished: "2014",
    isPdf: 0,
  },
  {
    SlNo: 37,
    BookId: 42,
    BookName: "বাংলাদেশের লোকশিল্প",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "",
    Category: "লোকশিল্প",
    YearOfPublished: "1995",
    isPdf: 0,
  },
  {
    SlNo: 38,
    BookId: 43,
    BookName: "বাংলাদেশের গৌরবগাঁথা আমাদেরই নকশিকাঁথা",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "",
    Category: "বাংলাদেশের কারুশিল্প",
    YearOfPublished: "2016",
    isPdf: 0,
  },
  {
    SlNo: 39,
    BookId: 44,
    BookName: "ভালোবাসার তামা কাঁসা পিতল",
    BookImg: "book-large.jpg",
    Author: "সাগর অনন্ত",
    Editor: "-",
    Category: "কারুশিল্প ",
    YearOfPublished: "2019",
    isPdf: 0,
  },
  {
    SlNo: 50,
    BookId: 57,
    BookName: "পশ্চিম সীমান্ত বঙ্গের লোক সাহিত্য",
    BookImg: "book-large.jpg",
    Author: "সুভাষ বন্দ্যোপাধ্যায়",
    Editor: "",
    Category: "লোক সাহিত্য",
    YearOfPublished: "1969",
    isPdf: 0,
  },
  {
    SlNo: 80,
    BookId: 87,
    BookName: "লোক সাহিত্য জালালাবাদ",
    BookImg: "book-large.jpg",
    Author: "মুহম্মদ আসাদ্দর আলী",
    Editor: "",
    Category: "লোক সাহিত্য",
    YearOfPublished: "1995",
    isPdf: 0,
  },
  {
    SlNo: 119,
    BookId: 131,
    BookName: "লোকসংস্কৃতির স্বরূপ  ",
    BookImg: "book-large.jpg",
    Author: "মাহমুদ শফিক",
    Editor: "-",
    Category: "লোক সংস্কৃতি",
    YearOfPublished: "2006",
    isPdf: 0,
  },
  {
    SlNo: 125,
    BookId: 137,
    BookName: "বাংলাদেশের লোকশিল্প",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "সৈয়দ মাহমুদূল হাসান",
    Category: "লোকশিল্প",
    YearOfPublished: "1983",
    isPdf: 0,
  },
  {
    SlNo: 129,
    BookId: 141,
    BookName: "লোকসংস্কৃতি",
    BookImg: "book-large.jpg",
    Author: "মাহমুদ শফিক",
    Editor: "-",
    Category: "লোক সংস্কৃতি",
    YearOfPublished: "2005",
    isPdf: 0,
  },
  {
    SlNo: 132,
    BookId: 144,
    BookName: "কারুশিল্পীদের তালিকা",
    BookImg: "book-large.jpg",
    Author: "বাংলাদেশ লোক ও কারুশিল্প ফাউন্ডেশন",
    Editor: "মাহমুদ শফিক",
    Category: "লোকশিল্প",
    YearOfPublished: "2005",
    isPdf: 0,
  },
  {
    SlNo: 133,
    BookId: 145,
    BookName: "কারুশিল্পীদের তালিকা",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "মাহমুদ শফিক",
    Category: "কারুশিল্প ",
    YearOfPublished: "2005",
    isPdf: 0,
  },
  {
    SlNo: 134,
    BookId: 146,
    BookName: "লোকশিল্প ",
    BookImg: "book-large.jpg",
    Author: "সৈয়দ মাহবুব আলম",
    Editor: "-",
    Category: "লোকশিল্প",
    YearOfPublished: "1999",
    isPdf: 0,
  },
  {
    SlNo: 135,
    BookId: 147,
    BookName: "বাংলাদেশের কারুপণ্য",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "মাহমুদ শফিক",
    Category: "লোকশিল্প",
    YearOfPublished: "2005",
    isPdf: 0,
  },
  {
    SlNo: 138,
    BookId: 150,
    BookName: "লোকশিল্প ",
    BookImg: "book-large.jpg",
    Author: "সৈয়দ মাহবুব আলম",
    Editor: "-",
    Category: "লোকশিল্প",
    YearOfPublished: "1999",
    isPdf: 0,
  },
  {
    SlNo: 145,
    BookId: 157,
    BookName: "বাংলাদেশের লোকশিল্প",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "এল কে এম শামসুল হক",
    Category: "লোকশিল্প",
    YearOfPublished: "1983",
    isPdf: 0,
  },
  {
    SlNo: 146,
    BookId: 158,
    BookName: "লোকশিল্প ",
    BookImg: "book-large.jpg",
    Author: "সৈয়দ মাহবুব আলম",
    Editor: "-",
    Category: "লোকশিল্প",
    YearOfPublished: "1999",
    isPdf: 0,
  },
  {
    SlNo: 151,
    BookId: 163,
    BookName: "বাংলাদেশের লোকশিল্প",
    BookImg: "book-large.jpg",
    Author: "-",
    Editor: "সৈয়দ মাহমুদূল হাসান",
    Category: "লোকশিল্প",
    YearOfPublished: "1983",
    isPdf: 0,
  },
  {
    SlNo: 152,
    BookId: 164,
    BookName: "নদী পাড়ের বিলুপ্ত প্রায় লোক ও কারুশিল্প ",
    BookImg: "book-large.jpg",
    Author: "বিলু কবীর",
    Editor: "",
    Category: "কারুশিল্প ",
    YearOfPublished: "2017",
    isPdf: 0,
  },
  {
    SlNo: 153,
    BookId: 165,
    BookName: "বাংলাদেশের লোকশিল্প",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "সৈয়দ মাহমুদূল হাসান",
    Category: "লোকশিল্প",
    YearOfPublished: "1983",
    isPdf: 0,
  },
  {
    SlNo: 154,
    BookId: 166,
    BookName: "বাংলাদেশের লোকশিল্প",
    BookImg: "book-large.jpg",
    Author: "-",
    Editor: "সৈয়দ মাহমুদুল হাসান ",
    Category: "লোকশিল্প",
    YearOfPublished: "1983",
    isPdf: 0,
  },
  {
    SlNo: 155,
    BookId: 167,
    BookName: "নদী পাড়ের বিলুপ্ত প্রায় লোক ও কারুশিল্প ",
    BookImg: "book-large.jpg",
    Author: "বিলু কবীর",
    Editor: "-",
    Category: "কারুশিল্প ",
    YearOfPublished: "2017",
    isPdf: 0,
  },
  {
    SlNo: 156,
    BookId: 168,
    BookName: " লোকশিল্প",
    BookImg: "book-large.jpg",
    Author: "সৈয়দ মাহবুব আলম",
    Editor: "",
    Category: "লোকশিল্প",
    YearOfPublished: "1999",
    isPdf: 0,
  },
  {
    SlNo: 157,
    BookId: 170,
    BookName: "লোকশিল্প ",
    BookImg: "book-large.jpg",
    Author: "সৈয়দ মাহবুব আলম",
    Editor: "-",
    Category: "লোকশিল্প",
    YearOfPublished: "1999",
    isPdf: 0,
  },
  {
    SlNo: 158,
    BookId: 171,
    BookName: "লোকশিল্প ",
    BookImg: "book-large.jpg",
    Author: "সৈয়দ মাহবুব আলম",
    Editor: "",
    Category: "লোকশিল্প",
    YearOfPublished: "1999",
    isPdf: 0,
  },
  {
    SlNo: 160,
    BookId: 173,
    BookName: "বাংলাদেশের লোকশিল্প",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "সৈয়দ মাহমুদূল হাসান",
    Category: "লোকশিল্প",
    YearOfPublished: "1983",
    isPdf: 0,
  },
  {
    SlNo: 161,
    BookId: 174,
    BookName: "বাংলাদেশের লোকশিল্প",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "সৈয়দ মাহমুদূল হাসান",
    Category: "লোকশিল্প",
    YearOfPublished: "1995",
    isPdf: 0,
  },
  {
    SlNo: 172,
    BookId: 185,
    BookName: "বাংলা একাডেমী বৈশাখী লোক -উ’সব প্রবন্ধ ১৪০০",
    BookImg: "book-large.jpg",
    Author: "-",
    Editor: "-",
    Category: "বাংলা সাহিত্য",
    YearOfPublished: "1993",
    isPdf: 0,
  },
  {
    SlNo: 178,
    BookId: 191,
    BookName: "মানুষের আদি উৎস",
    BookImg: "book-large.jpg",
    Author: "ড. মরিচ  বুকাইলি",
    Editor: "-",
    Category: "নৃবিজ্ঞান",
    YearOfPublished: "1996",
    isPdf: 0,
  },
  {
    SlNo: 189,
    BookId: 202,
    BookName: "বাংলাদেশে ফোকলোর চর্চার ইতিবৃত্ত ও অন্যান্য প্রবন্ধ",
    BookImg: "book-large.jpg",
    Author: "ড.তসিকুর ইসলাম",
    Editor: "-",
    Category: "ফোকলোর",
    YearOfPublished: "2004",
    isPdf: 0,
  },
  {
    SlNo: 196,
    BookId: 209,
    BookName: "পূর্ববঙ্গের বিভিন্ন জাতি, বর্ণ ও পেশার বিবরণ ",
    BookImg: "book-large.jpg",
    Author: "জেমস ওয়াইজ",
    Editor: "-",
    Category: "সমাজ ও সংস্কৃতি--উপজাতি",
    YearOfPublished: "2000",
    isPdf: 0,
  },
  {
    SlNo: 206,
    BookId: 220,
    BookName: "লোকসংস্কৃতি বিবেচনা ও অন্যান্য প্রসঙ্গ",
    BookImg: "book-large.jpg",
    Author: "আবুল আহসান চৌধুরী",
    Editor: "",
    Category: "লোক সংস্কৃতি",
    YearOfPublished: "1997",
    isPdf: 0,
  },
  {
    SlNo: 209,
    BookId: 223,
    BookName: "আদিম সমাজ ",
    BookImg: "book-large.jpg",
    Author: "লুইস হেনরি মর্গান",
    Editor: "-",
    Category: "আদিম সমাজ ব্যবস্থা",
    YearOfPublished: "2000",
    isPdf: 0,
  },
  {
    SlNo: 214,
    BookId: 228,
    BookName: "মধ্যবিত্ত সমাজের বিকাশ সংস্কৃতির রূপান্তর",
    BookImg: "book-large.jpg",
    Author: "আবদুল মওদুদ ",
    Editor: "",
    Category: "সংস্কৃতি বাংলাদেশ",
    YearOfPublished: "1969",
    isPdf: 0,
  },
  {
    SlNo: 247,
    BookId: 261,
    BookName: "চট্টগ্রামের সমাজ ও সংস্কৃতির রূপরেখা",
    BookImg: "book-large.jpg",
    Author: "আবদুল হক চৌধুরী",
    Editor: "-",
    Category: "লোক সংস্কৃতি",
    YearOfPublished: "1988",
    isPdf: 0,
  },
  {
    SlNo: 258,
    BookId: 272,
    BookName: "নরসিংদীর লৌকিক খেলাধুলা",
    BookImg: "book-large.jpg",
    Author: "মোহাম্মাদ হাবিবুল্লাহ পাঠান",
    Editor: "-",
    Category: "লোক সংস্কৃতি",
    YearOfPublished: "1988",
    isPdf: 0,
  },
  {
    SlNo: 261,
    BookId: 275,
    BookName: "মধ্যযুগের সাহিত্য সমাজ ও সংস্কৃতির রূপ",
    BookImg: "book-large.jpg",
    Author: "আহমদ শরীফ",
    Editor: "-",
    Category: "বাংলা সাহিত্য",
    YearOfPublished: "1980",
    isPdf: 0,
  },
  {
    SlNo: 277,
    BookId: 293,
    BookName: "বাংলাদেশের লোকশিল্প",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "",
    Category: "কারুশিল্প ",
    YearOfPublished: "1988",
    isPdf: 0,
  },
  {
    SlNo: 296,
    BookId: 312,
    BookName: "লোক ও কারুশিল্প পত্রিকা",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "আহমেদ উল্লাহ",
    Category: "পত্রিকা",
    YearOfPublished: "2021",
    isPdf: 0,
  },
  {
    SlNo: 298,
    BookId: 315,
    BookName: "লোক ও কারুশিল্প পত্রিকা   ",
    BookImg: "book-large.jpg",
    Author: "বাংলাদেশ লোক ও কারুশিল্প ফাউন্ডেশন",
    Editor: "-",
    Category: "পত্রিকা",
    YearOfPublished: "2022",
    isPdf: 0,
  },
  {
    SlNo: 299,
    BookId: 316,
    BookName: "সমাজতন্ত্রে বসবাস",
    BookImg: "book-large.jpg",
    Author: "দ্বিজেন শর্মা",
    Editor: "",
    Category: "সমাজবিজ্ঞান",
    YearOfPublished: "1999",
    isPdf: 0,
  },
  {
    SlNo: 325,
    BookId: 342,
    BookName: "সামাজিক ইতিহাস ও উন্নয়ন ভাবনা ",
    BookImg: "book-large.jpg",
    Author: "মোহাম্মদ হাবিবুর রহমান",
    Editor: "-",
    Category: "ইতিহাস- বাংলাদেশ",
    YearOfPublished: "1999",
    isPdf: 0,
  },
  {
    SlNo: 340,
    BookId: 357,
    BookName: "সংস্কৃতির সহজকথা",
    BookImg: "book-large.jpg",
    Author: "আবুল কাসেম ফজলুল হক",
    Editor: "",
    Category: "লোক সংস্কৃতি",
    YearOfPublished: "2002",
    isPdf: 0,
  },
  {
    SlNo: 343,
    BookId: 360,
    BookName: "ঐতিহাসিক সোনারগাঁ",
    BookImg: "book-large.jpg",
    Author: "একেএম মুজ্জাম্মিল হক",
    Editor: "-",
    Category: "প্রত্নতত্ত্ব-বাংলাদেশ",
    YearOfPublished: "2016",
    isPdf: 0,
  },
  {
    SlNo: 346,
    BookId: 364,
    BookName: "আঙ্গিকতার আলোকে ফোকলোর ",
    BookImg: "book-large.jpg",
    Author: "মযহারুল ইসলাম",
    Editor: "-",
    Category: "ফোকলোর",
    YearOfPublished: "1999",
    isPdf: 0,
  },
  {
    SlNo: 348,
    BookId: 366,
    BookName: "ভারতশিল্পের কথা",
    BookImg: "book-large.jpg",
    Author: "অখয় কুমার মৈত্রের",
    Editor: "-",
    Category: "ভারতীয় উপমহাদেশের ইতিহাস",
    YearOfPublished: "1980",
    isPdf: 0,
  },
  {
    SlNo: 353,
    BookId: 371,
    BookName: "বাংলাদেশের কারুপণ্য ",
    BookImg: "book-large.jpg",
    Author: "-",
    Editor: "মাহমুদ শফিক",
    Category: "লোকশিল্প",
    YearOfPublished: "2010",
    isPdf: 0,
  },
  {
    SlNo: 354,
    BookId: 372,
    BookName: "ভালোবাসার তামা কাঁসা পিতল",
    BookImg: "book-large.jpg",
    Author: "সাগর অনন্ত",
    Editor: "",
    Category: "লোকশিল্প",
    YearOfPublished: "2019",
    isPdf: 0,
  },
  {
    SlNo: 358,
    BookId: 376,
    BookName: "বাংলাদেশের ঐতিহ্যবাহী বাদ্যযন্ত্র",
    BookImg: "book-large.jpg",
    Author: "-",
    Editor: "-",
    Category: "বাদ্যযন্ত্র-বাংলাদেশ",
    YearOfPublished: "2013",
    isPdf: 0,
  },
  {
    SlNo: 361,
    BookId: 379,
    BookName: "বাংলাদেশের ঐতিহ্যবাহী বাদ্যযন্ত্র",
    BookImg: "book-large.jpg",
    Author: "-",
    Editor: "-",
    Category: "বাদ্যযন্ত্র-বাংলাদেশ",
    YearOfPublished: "2013",
    isPdf: 0,
  },
  {
    SlNo: 363,
    BookId: 381,
    BookName: "ভালোবাসার তামা কাঁসা পিতল",
    BookImg: "book-large.jpg",
    Author: "সাগর অনন্ত",
    Editor: "-",
    Category: "লোকশিল্প",
    YearOfPublished: "2019",
    isPdf: 0,
  },
  {
    SlNo: 364,
    BookId: 382,
    BookName: "রক্তকরবী",
    BookImg: "book-large.jpg",
    Author: "রবীন্দ্রনাথ ঠাকুর",
    Editor: "",
    Category: "বাংলা উপন্যাস",
    YearOfPublished: "1997",
    isPdf: 0,
  },
  {
    SlNo: 366,
    BookId: 384,
    BookName: "পুনশ্চ",
    BookImg: "book-large.jpg",
    Author: "রবীন্দ্রনাথ ঠাকুর",
    Editor: "",
    Category: "বাংলা উপন্যাস",
    YearOfPublished: "1994",
    isPdf: 0,
  },
  {
    SlNo: 371,
    BookId: 389,
    BookName: "পূরবী",
    BookImg: "book-large.jpg",
    Author: "রবীন্দ্রনাথ ঠাকুর",
    Editor: "",
    Category: "বাংলা কবিতা",
    YearOfPublished: "1997",
    isPdf: 0,
  },
  {
    SlNo: 376,
    BookId: 394,
    BookName: "লিপিকা",
    BookImg: "book-large.jpg",
    Author: "রবীন্দ্রনাথ ঠাকুর",
    Editor: "",
    Category: "বাংলা উপন্যাস",
    YearOfPublished: "1997",
    isPdf: 0,
  },
  {
    SlNo: 379,
    BookId: 397,
    BookName: "রবীন্দ্রনাথ : কিশোর জীবনী",
    BookImg: "book-large.jpg",
    Author: "হায়াৎ মামুদ",
    Editor: "",
    Category: "জীবনী",
    YearOfPublished: "2000",
    isPdf: 0,
  },
  {
    SlNo: 380,
    BookId: 398,
    BookName: "প্রজাপতির নির্বন্ধ",
    BookImg: "book-large.jpg",
    Author: "রবীন্দ্রনাথ ঠাকুর",
    Editor: "",
    Category: "বাংলা নাটক",
    YearOfPublished: "1996",
    isPdf: 0,
  },
  {
    SlNo: 382,
    BookId: 400,
    BookName: "বিসর্জন",
    BookImg: "book-large.jpg",
    Author: "রবীন্দ্রনাথ ঠাকুর",
    Editor: "",
    Category: "বাংলা নাটক",
    YearOfPublished: "1996",
    isPdf: 0,
  },
  {
    SlNo: 387,
    BookId: 405,
    BookName: "নৌকাডুবি",
    BookImg: "book-large.jpg",
    Author: "রবীন্দ্রনাথ ঠাকুর",
    Editor: "",
    Category: "বাংলা উপন্যাস",
    YearOfPublished: "1995",
    isPdf: 0,
  },
  {
    SlNo: 388,
    BookId: 406,
    BookName: "গীতাঞ্জলী",
    BookImg: "book-large.jpg",
    Author: "রবীন্দ্রনাথ ঠাকুর",
    Editor: "",
    Category: "বাংলা কবিতা",
    YearOfPublished: "2013",
    isPdf: 0,
  },
  {
    SlNo: 390,
    BookId: 408,
    BookName: "উপন্যাসসমগ্র",
    BookImg: "book-large.jpg",
    Author: "রবীন্দ্রনাথ ঠাকুর",
    Editor: "",
    Category: "বাংলা উপন্যাস",
    YearOfPublished: "1999",
    isPdf: 0,
  },
  {
    SlNo: 393,
    BookId: 411,
    BookName: "নজরুল -শব্দপঞ্জি",
    BookImg: "book-large.jpg",
    Author: "হাকিম আরিফ",
    Editor: "",
    Category: "অভিধান",
    YearOfPublished: "1997",
    isPdf: 0,
  },
  {
    SlNo: 397,
    BookId: 415,
    BookName: "ত্রিপুরায় অন্য রবীন্দ্রনাথ",
    BookImg: "book-large.jpg",
    Author: "খগেশ দেববর্মন",
    Editor: "",
    Category: "বাংলা সাহিত্য",
    YearOfPublished: "2007",
    isPdf: 0,
  },
  {
    SlNo: 400,
    BookId: 418,
    BookName: "উপন্যাসসমগ্র",
    BookImg: "book-large.jpg",
    Author: "রবীন্দ্রনাথ ঠাকুর",
    Editor: "",
    Category: "বাংলা উপন্যাস",
    YearOfPublished: "1999",
    isPdf: 0,
  },
  {
    SlNo: 404,
    BookId: 422,
    BookName: "কিশোর সাহিত্যসমগ্র্র্র্র্র্র্র্র্র্র্র্র্র্র্র্র্র্র্র",
    BookImg: "book-large.jpg",
    Author: "রবীন্দ্রনাথ ঠাকুর",
    Editor: "",
    Category: "বাংলা সাহিত্য",
    YearOfPublished: "1993",
    isPdf: 0,
  },
  {
    SlNo: 406,
    BookId: 424,
    BookName: "কিশোর সাহিত্যসমগ্র্র্র্র্র্র্র্র্র্র্র্র্র্র্র্র্র্র্র",
    BookImg: "book-large.jpg",
    Author: "রবীন্দ্রনাথ ঠাকুর",
    Editor: "",
    Category: "বাংলা সাহিত্য",
    YearOfPublished: "1993",
    isPdf: 0,
  },
  {
    SlNo: 408,
    BookId: 426,
    BookName: "নজরুল রচনাবলী ১ম খন্ড   কবি কাজী নজরুল ইসলমা",
    BookImg: "book-large.jpg",
    Author: "কবি কাজী নজরুল ইসলমা",
    Editor: "",
    Category: "বাংলা সাহিত্য",
    YearOfPublished: "1984",
    isPdf: 0,
  },
  {
    SlNo: 411,
    BookId: 429,
    BookName: "নজরুল রচনাবলী ১ম খন্ড   ",
    BookImg: "book-large.jpg",
    Author: "কবি কাজী নজরুল ইসলমা",
    Editor: "",
    Category: "বাংলা সাহিত্য",
    YearOfPublished: "1984",
    isPdf: 0,
  },
  {
    SlNo: 412,
    BookId: 430,
    BookName: "নজরুল রচনাবলী ১ম খন্ড   ",
    BookImg: "book-large.jpg",
    Author: "কবি কাজী নজরুল ইসলমা",
    Editor: "",
    Category: "বাংলা কবিতা",
    YearOfPublished: "1984",
    isPdf: 0,
  },
  {
    SlNo: 415,
    BookId: 433,
    BookName: "নজরুল রচনাবলী ৫ম খন্ড  দ্বিতীয়ার্থ ",
    BookImg: "book-large.jpg",
    Author: "কবি কাজী নজরুল ইসলমা",
    Editor: "",
    Category: "বাংলা সাহিত্য",
    YearOfPublished: "1984",
    isPdf: 0,
  },
  {
    SlNo: 417,
    BookId: 435,
    BookName: "নজরুল রচনাবলী ৫ম খন্ড  দ্বিতীয়ার্থ ",
    BookImg: "book-large.jpg",
    Author: "কবি কাজী নজরুল ইসলমা",
    Editor: "",
    Category: "বাংলা সাহিত্য",
    YearOfPublished: "1984",
    isPdf: 0,
  },
  {
    SlNo: 426,
    BookId: 444,
    BookName: "আধুনিক রবীন্দ্রনাথ ",
    BookImg: "book-large.jpg",
    Author: "আবু সাইদ আইয়ুব",
    Editor: "",
    Category: "বাংলা সাহিত্য",
    YearOfPublished: "1976",
    isPdf: 0,
  },
  {
    SlNo: 429,
    BookId: 447,
    BookName: "জীবনে সমাজে সাহিত্যে",
    BookImg: "book-large.jpg",
    Author: "আহমদ শরীফ",
    Editor: "",
    Category: "বাংলা সাহিত্য",
    YearOfPublished: "2001",
    isPdf: 0,
  },
  {
    SlNo: 430,
    BookId: 448,
    BookName: "শেষের কবিতা",
    BookImg: "book-large.jpg",
    Author: "রবীন্দ্রনাথ ঠাকুর",
    Editor: "",
    Category: "বাংলা কবিতা",
    YearOfPublished: "2013",
    isPdf: 0,
  },
  {
    SlNo: 435,
    BookId: 453,
    BookName: "রবীন্দ্রনাথ ঠাকুরের শ্রেষ্ঠ কবিতা",
    BookImg: "book-large.jpg",
    Author: "রবীন্দ্রনাথ ঠাকুর",
    Editor: "",
    Category: "বাংলা কবিতা",
    YearOfPublished: "2007",
    isPdf: 0,
  },
  {
    SlNo: 437,
    BookId: 455,
    BookName: "শতবর্ষে নজরুল",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "",
    Category: "বাংলা সাহিত্য",
    YearOfPublished: "2001",
    isPdf: 0,
  },
  {
    SlNo: 448,
    BookId: 466,
    BookName: "উপন্যাসসমগ্র",
    BookImg: "book-large.jpg",
    Author: "রবীন্দ্রনাথ ঠাকুর",
    Editor: "",
    Category: "বাংলা উপন্যাস",
    YearOfPublished: "1999",
    isPdf: 0,
  },
  {
    SlNo: 450,
    BookId: 468,
    BookName: "নজরুল গীতি প্রসঙ্গ",
    BookImg: "book-large.jpg",
    Author: "করুণাময়",
    Editor: "",
    Category: "নজরুল সঙ্গীত ",
    YearOfPublished: "1996",
    isPdf: 0,
  },
  {
    SlNo: 454,
    BookId: 472,
    BookName: "নান্দনিক নজরুল ",
    BookImg: "book-large.jpg",
    Author: "মুহম্মদ নূরুল হুদা",
    Editor: "",
    Category: "জীবনী মূলক",
    YearOfPublished: "2001",
    isPdf: 0,
  },
  {
    SlNo: 455,
    BookId: 473,
    BookName: "নান্দনিক নজরুল ",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "",
    Category: "জীবনী মূলক",
    YearOfPublished: "2001",
    isPdf: 0,
  },
  {
    SlNo: 458,
    BookId: 476,
    BookName: "নজারুল গীতিকা",
    BookImg: "book-large.jpg",
    Author: "কাজী নজরুল ইসলাম",
    Editor: "",
    Category: "নজরুল সঙ্গীত ",
    YearOfPublished: "2002",
    isPdf: 0,
  },
  {
    SlNo: 460,
    BookId: 478,
    BookName: "তোমার সাম্রাজ্যে, যুবরাজ",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "",
    Category: "বাংলা সাহিত্য",
    YearOfPublished: "1999",
    isPdf: 0,
  },
  {
    SlNo: 464,
    BookId: 482,
    BookName: "সুর শিরাজী",
    BookImg: "book-large.jpg",
    Author: "সৈয়দ শামসুল হুদা",
    Editor: "",
    Category: "নজরুল সংগীত",
    YearOfPublished: "1999",
    isPdf: 0,
  },
  {
    SlNo: 468,
    BookId: 486,
    BookName: "নজরুল ও তাঁর বৈরীপক্ষ",
    BookImg: "book-large.jpg",
    Author: "আনোয়ারুল হক",
    Editor: "",
    Category: "জীবনী ও কর্ম",
    YearOfPublished: "2000",
    isPdf: 0,
  },
  {
    SlNo: 470,
    BookId: 488,
    BookName: "কথাশিল্পী নজরুল",
    BookImg: "book-large.jpg",
    Author: "রাজিয়া সুলতানা",
    Editor: "",
    Category: "বাংলা সাহিত্য",
    YearOfPublished: "2000",
    isPdf: 0,
  },
  {
    SlNo: 472,
    BookId: 490,
    BookName: "শতবর্ষের মুল্যায়ন: নজরুল-সঙ্গীত",
    BookImg: "book-large.jpg",
    Author: "ইদসি আলী ",
    Editor: "",
    Category: "নজরুল সংগীত",
    YearOfPublished: "2001",
    isPdf: 0,
  },
  {
    SlNo: 475,
    BookId: 493,
    BookName: "সঙ্গীতে নজরুল-সঙ্গীত ",
    BookImg: "book-large.jpg",
    Author: "শফি চাকরাদার",
    Editor: "",
    Category: "নজরুল সংগীত",
    YearOfPublished: "2012",
    isPdf: 0,
  },
  {
    SlNo: 477,
    BookId: 495,
    BookName: "লোকায়ত নজরুল",
    BookImg: "book-large.jpg",
    Author: "সেলিম জাহাঙ্গীর",
    Editor: "",
    Category: "বাংলা উপন্যাস",
    YearOfPublished: "1997",
    isPdf: 0,
  },
  {
    SlNo: 483,
    BookId: 501,
    BookName: "গীতি-শতদল",
    BookImg: "book-large.jpg",
    Author: "কাজী নজরুল ইসলাম",
    Editor: "",
    Category: "নজরুল সংগীত",
    YearOfPublished: "2002",
    isPdf: 0,
  },
  {
    SlNo: 484,
    BookId: 502,
    BookName: "চুরুলিয়ার যাত্রী",
    BookImg: "book-large.jpg",
    Author: "আসাদুল হক",
    Editor: "",
    Category: "বাংলা উপন্যাস",
    YearOfPublished: "2000",
    isPdf: 0,
  },
  {
    SlNo: 485,
    BookId: 503,
    BookName: "ঝড়",
    BookImg: "book-large.jpg",
    Author: "কাজী নজরুল ইসলাম",
    Editor: "",
    Category: "বাংলা কবিতা",
    YearOfPublished: "1997",
    isPdf: 0,
  },
  {
    SlNo: 486,
    BookId: 504,
    BookName: "শিউলি-মালা",
    BookImg: "book-large.jpg",
    Author: "কাজী নজরুল ইসলাম",
    Editor: "-",
    Category: "বাংলা উপন্যাস",
    YearOfPublished: "2002",
    isPdf: 0,
  },
  {
    SlNo: 490,
    BookId: 508,
    BookName: "কুহেলিকা",
    BookImg: "book-large.jpg",
    Author: "কাজী নজরুল ইসলাম",
    Editor: "-",
    Category: "বাংলা উপন্যাস",
    YearOfPublished: "1980",
    isPdf: 0,
  },
  {
    SlNo: 492,
    BookId: 510,
    BookName: "বিষের বাঁশী: বিষয় ও প্রকরণ ",
    BookImg: "book-large.jpg",
    Author: "খায়রুল আনাম খান ",
    Editor: "",
    Category: "বাংলা উপন্যাস",
    YearOfPublished: "",
    isPdf: 0,
  },
  {
    SlNo: 494,
    BookId: 512,
    BookName: "মহুয়ার গান",
    BookImg: "book-large.jpg",
    Author: "কাজী নজরুল ইসলাম",
    Editor: "",
    Category: "লোক সংগীত",
    YearOfPublished: "1930",
    isPdf: 0,
  },
  {
    SlNo: 498,
    BookId: 516,
    BookName: "সর্বহারা",
    BookImg: "book-large.jpg",
    Author: "কবি কাজী নজরুল ইসলম",
    Editor: "",
    Category: "বাংলা কবিতা",
    YearOfPublished: "",
    isPdf: 0,
  },
  {
    SlNo: 509,
    BookId: 527,
    BookName: "চন্দ্রবিন্দু",
    BookImg: "book-large.jpg",
    Author: "কবি কাজী নজরুল ইসলাম",
    Editor: "",
    Category: "বাংলা কবিতা",
    YearOfPublished: "2002",
    isPdf: 0,
  },
  {
    SlNo: 512,
    BookId: 530,
    BookName: "নজরুলের কবিতায় মিথ ও লোকজ উপাদান ",
    BookImg: "book-large.jpg",
    Author: "মাহবুব হাসান",
    Editor: "",
    Category: "বাংলা সাহিত্য",
    YearOfPublished: "2001",
    isPdf: 0,
  },
  {
    SlNo: 515,
    BookId: 533,
    BookName: "মোসলেম ভারত ও অন্যান্য প্রসঙ্গ ",
    BookImg: "book-large.jpg",
    Author: "মো: মনিরুল ইসলাম",
    Editor: "",
    Category: "প্রবন্ধ",
    YearOfPublished: "2001",
    isPdf: 0,
  },
  {
    SlNo: 517,
    BookId: 535,
    BookName: "নজরুলের প্রবন্ধ সাহিত্য",
    BookImg: "book-large.jpg",
    Author: "মনোয়ারা  হোসেন",
    Editor: "",
    Category: "প্রবন্ধ",
    YearOfPublished: "2000",
    isPdf: 0,
  },
  {
    SlNo: 520,
    BookId: 538,
    BookName: "সৃষ্টি সুখের উল্লাসে",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "",
    Category: "জীবনী ও কর্ম",
    YearOfPublished: "1980",
    isPdf: 0,
  },
  {
    SlNo: 522,
    BookId: 540,
    BookName: "শিল্পিত নজরুল অন্বেষিত অপচয় ",
    BookImg: "book-large.jpg",
    Author: "ড. মো. হারুন-অর-রশীদ",
    Editor: "",
    Category: "জীবনী ও কর্ম",
    YearOfPublished: "2004",
    isPdf: 0,
  },
  {
    SlNo: 524,
    BookId: 542,
    BookName: "নজরুলের নির্বাচিত প্রবন্ধ",
    BookImg: "book-large.jpg",
    Author: "-",
    Editor: "-",
    Category: "প্রবন্ধ",
    YearOfPublished: "1997",
    isPdf: 0,
  },
  {
    SlNo: 532,
    BookId: 550,
    BookName: "বাংলাদেশের দারুশিল্প",
    BookImg: "book-large.jpg",
    Author: "জিনাত মাহরুখ বানু",
    Editor: "-",
    Category: "দারুশিল্প",
    YearOfPublished: "2003",
    isPdf: 0,
  },
  {
    SlNo: 534,
    BookId: 552,
    BookName: "নজরুল ও অন্যান্য প্রসঙ্গ",
    BookImg: "book-large.jpg",
    Author: "আবুল কালাম জনজুর মোরশেদ",
    Editor: "",
    Category: "জীবনী ও কর্ম",
    YearOfPublished: "2001",
    isPdf: 0,
  },
  {
    SlNo: 559,
    BookId: 577,
    BookName: "ধর্মীয় চেতনায় নজরুল",
    BookImg: "book-large.jpg",
    Author: "কামরুন্নেছা আজাদ",
    Editor: "",
    Category: "জীবনী মূলক",
    YearOfPublished: "2001",
    isPdf: 0,
  },
  {
    SlNo: 562,
    BookId: 580,
    BookName: "নজরুল সাহিত্যে যুবশক্তি",
    BookImg: "book-large.jpg",
    Author: "শামীম আরা সুইটী",
    Editor: "",
    Category: "বাংলা সাহিত্য",
    YearOfPublished: "1997",
    isPdf: 0,
  },
  {
    SlNo: 565,
    BookId: 583,
    BookName: "নজরুল সঙ্গীতের রূপকার ",
    BookImg: "book-large.jpg",
    Author: "আসাদুল হক",
    Editor: "",
    Category: "জীবনী মূলক",
    YearOfPublished: "1990",
    isPdf: 0,
  },
  {
    SlNo: 566,
    BookId: 584,
    BookName: "নজরুলের পত্রাবলী",
    BookImg: "book-large.jpg",
    Author: "-",
    Editor: "",
    Category: "পত্রাবলী",
    YearOfPublished: "",
    isPdf: 0,
  },
  {
    SlNo: 569,
    BookId: 587,
    BookName: "নজরুল-প্রতিভার স্বরূপ",
    BookImg: "book-large.jpg",
    Author: "আবদুল কাদির ",
    Editor: "",
    Category: "জীবনী ও কর্ম",
    YearOfPublished: "1989",
    isPdf: 0,
  },
  {
    SlNo: 571,
    BookId: 589,
    BookName: "আধুনিক বাংলা কবিতা শব্দের অনুষঙ্গে",
    BookImg: "book-large.jpg",
    Author: " সৈয়দ আলী আহসান",
    Editor: "",
    Category: "বাংলা কবিতা",
    YearOfPublished: "2001",
    isPdf: 0,
  },
  {
    SlNo: 574,
    BookId: 592,
    BookName: "নজরুল-চরিতমালা",
    BookImg: "book-large.jpg",
    Author: "ড: সুশীলকুমার গুপ্ত",
    Editor: "",
    Category: "জীবনী মূলক",
    YearOfPublished: "1980",
    isPdf: 0,
  },
  {
    SlNo: 575,
    BookId: 593,
    BookName: "নজরুল বর্ণালী ",
    BookImg: "book-large.jpg",
    Author: "আতোয়ার রহমান",
    Editor: "",
    Category: "জীবনী মূলক",
    YearOfPublished: "1994",
    isPdf: 0,
  },
  {
    SlNo: 578,
    BookId: 596,
    BookName: "নজরুল জন্মশতবর্ষ বক্তৃতামালা",
    BookImg: "book-large.jpg",
    Author: "আলাউদ্দিন আল আজাদ",
    Editor: "",
    Category: "বাণী ",
    YearOfPublished: "1995",
    isPdf: 0,
  },
  {
    SlNo: 586,
    BookId: 604,
    BookName: "বাংলাদেশে নজরুল চর্চা মুখোশ ও বাস্তবতা",
    BookImg: "book-large.jpg",
    Author: "আবদুল হাই শিকদার",
    Editor: "",
    Category: "বাংলা সাহিত্য সমালোচনা",
    YearOfPublished: "2003",
    isPdf: 0,
  },
  {
    SlNo: 588,
    BookId: 606,
    BookName: "নজরুল প্রসঙ্গে",
    BookImg: "book-large.jpg",
    Author: "রফিকুল ইসলাম ",
    Editor: "",
    Category: "জীবনী মূলক",
    YearOfPublished: "1998",
    isPdf: 0,
  },
  {
    SlNo: 600,
    BookId: 618,
    BookName: "নজরুল বলয়ে প্রদক্ষিণ ",
    BookImg: "book-large.jpg",
    Author: "সিদ্দিকুর রহমান",
    Editor: "",
    Category: "সমালোচনা",
    YearOfPublished: "2000",
    isPdf: 0,
  },
  {
    SlNo: 604,
    BookId: 622,
    BookName: "নবযুগ ও নজরুল",
    BookImg: "book-large.jpg",
    Author: "শিরীণ আখতার",
    Editor: "",
    Category: "সমালোচনা",
    YearOfPublished: "2001",
    isPdf: 0,
  },
  {
    SlNo: 608,
    BookId: 626,
    BookName: "নজরুল ইসলাম , কিশোর জীবনী",
    BookImg: "book-large.jpg",
    Author: "হায়াৎ মামুদ",
    Editor: "",
    Category: "জীবনী মূলক",
    YearOfPublished: "1995",
    isPdf: 0,
  },
  {
    SlNo: 609,
    BookId: 627,
    BookName: "প্রলয়-শিখা",
    BookImg: "book-large.jpg",
    Author: "কবি কাজী নজরুল ইসলাম",
    Editor: "",
    Category: "বাংলা কবিতা",
    YearOfPublished: "2003",
    isPdf: 0,
  },
  {
    SlNo: 611,
    BookId: 629,
    BookName: "আসানসোল কাজীরসিমলা ও দরিরামপুরে নজরুল",
    BookImg: "book-large.jpg",
    Author: "কাজী তালেবুর রহমান",
    Editor: "",
    Category: "সমালোচনা",
    YearOfPublished: "1994",
    isPdf: 0,
  },
  {
    SlNo: 612,
    BookId: 630,
    BookName: "প্রলয় কেতন",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "",
    Category: "সমালোচনা",
    YearOfPublished: "1992",
    isPdf: 0,
  },
  {
    SlNo: 618,
    BookId: 636,
    BookName: "নজরুলের গদ্যে উপমা",
    BookImg: "book-large.jpg",
    Author: "শাহাবুদ্দীন আহমদ",
    Editor: "",
    Category: "প্রবন্ধ",
    YearOfPublished: "2001",
    isPdf: 0,
  },
  {
    SlNo: 623,
    BookId: 641,
    BookName: "ইসলাম ঐতিহ্যে নজরুল সঙ্গীত",
    BookImg: "book-large.jpg",
    Author: "আসাদুল হক",
    Editor: "",
    Category: "নজরুল সংগীত",
    YearOfPublished: "2000",
    isPdf: 0,
  },
  {
    SlNo: 624,
    BookId: 642,
    BookName: "নজরুল কাব্যে আরবী ফারসী শব্দ",
    BookImg: "book-large.jpg",
    Author: "আবদুস সাত্তার ",
    Editor: "",
    Category: "বাংলা কবিতা",
    YearOfPublished: "1992",
    isPdf: 0,
  },
  {
    SlNo: 626,
    BookId: 645,
    BookName: "নজরুল-সঙ্গীত অভিধান",
    BookImg: "book-large.jpg",
    Author: "আবদুস সাত্তার ",
    Editor: "",
    Category: "নজরুল সঙ্গীত ",
    YearOfPublished: "1992",
    isPdf: 0,
  },
  {
    SlNo: 627,
    BookId: 646,
    BookName: "স্মৃতিকথায়",
    BookImg: "book-large.jpg",
    Author: "কাজী নজরুল ইসলাম",
    Editor: "",
    Category: "বাংলা সাহিত্য",
    YearOfPublished: "2001",
    isPdf: 0,
  },
  {
    SlNo: 631,
    BookId: 650,
    BookName: "সুর-মুকুর",
    BookImg: "book-large.jpg",
    Author: "কাজী নজরুল ইসলাম",
    Editor: "",
    Category: "নজরুল সংগীত",
    YearOfPublished: "2003",
    isPdf: 0,
  },
  {
    SlNo: 636,
    BookId: 655,
    BookName: "ছোটদের নজরুল জীবনী ",
    BookImg: "book-large.jpg",
    Author: "মুহম্মদ নূরুল হুদা",
    Editor: "",
    Category: "জীবনী মূলক",
    YearOfPublished: "2000",
    isPdf: 0,
  },
  {
    SlNo: 638,
    BookId: 657,
    BookName: "নজরুল-সংগীত স্বরলিপি",
    BookImg: "book-large.jpg",
    Author: "নিখিলরঞ্জ নাথ ",
    Editor: "",
    Category: "নজরুল সঙ্গীত ",
    YearOfPublished: "2002",
    isPdf: 0,
  },
  {
    SlNo: 641,
    BookId: 660,
    BookName: "মন্তব্য সাহিত্য",
    BookImg: "book-large.jpg",
    Author: "কাজী নজরুল ইসলাম",
    Editor: "",
    Category: "সমালোচনা",
    YearOfPublished: "2000",
    isPdf: 0,
  },
  {
    SlNo: 643,
    BookId: 662,
    BookName: "নজরুল ইন্সটিটিউট পত্রিকা",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "",
    Category: "বাংলা সাহিত্য",
    YearOfPublished: "2002",
    isPdf: 0,
  },
  {
    SlNo: 647,
    BookId: 666,
    BookName: "নজরুল ইন্সটিটিউট পত্রিকা",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "",
    Category: "বাংলা সাহিত্য",
    YearOfPublished: "2002",
    isPdf: 0,
  },
  {
    SlNo: 651,
    BookId: 670,
    BookName: "আদি স্বরলিপি সংগ্রহ",
    BookImg: "book-large.jpg",
    Author: "ব্রহ্মমোহন ঠাকুর ",
    Editor: "",
    Category: "নজরুল সঙ্গীত ",
    YearOfPublished: "1999",
    isPdf: 0,
  },
  {
    SlNo: 656,
    BookId: 675,
    BookName: "নজরুল-সঙ্গীত স্বরলিপি প্রথম খন্ড",
    BookImg: "book-large.jpg",
    Author: "সুধীন দাশ ",
    Editor: "",
    Category: "নজরুল সংগীত",
    YearOfPublished: "1986",
    isPdf: 0,
  },
  {
    SlNo: 659,
    BookId: 678,
    BookName: "নজরুলের সাংবাদিকতা",
    BookImg: "book-large.jpg",
    Author: "আবু হেনা আবদুল আউয়াল",
    Editor: "",
    Category: "সমালোচনা",
    YearOfPublished: "2000",
    isPdf: 0,
  },
  {
    SlNo: 660,
    BookId: 679,
    BookName: "নজরুলের গদ্যরচনা ভাবলোক ও শিল্পরূপ",
    BookImg: "book-large.jpg",
    Author: "সৈকত আসগর",
    Editor: "",
    Category: "বাংলা সাহিত্য",
    YearOfPublished: "1990",
    isPdf: 0,
  },
  {
    SlNo: 668,
    BookId: 687,
    BookName: "মুসলিম মুদ্রা ও হস্তলিখন শিল্প",
    BookImg: "book-large.jpg",
    Author: "ড. এ, কে .এম. ইয়াকুব আলী",
    Editor: "",
    Category: "হস্তশিল্প",
    YearOfPublished: "2001",
    isPdf: 0,
  },
  {
    SlNo: 671,
    BookId: 690,
    BookName: "কাঠ প্রযুক্তি বিদ্যা",
    BookImg: "book-large.jpg",
    Author: "অরুণ কুমার লাহিড়ী",
    Editor: "",
    Category: "হস্তশিল্প",
    YearOfPublished: "2003",
    isPdf: 0,
  },
  {
    SlNo: 680,
    BookId: 699,
    BookName: "Handcraft in wood and metal",
    BookImg: "book-large.jpg",
    Author: "John Hooper ",
    Editor: "",
    Category: "Folk Art ",
    YearOfPublished: "1913",
    isPdf: 0,
  },
  {
    SlNo: 683,
    BookId: 702,
    BookName: "Cross Stitch Gifts for Children",
    BookImg: "book-large.jpg",
    Author: "Jo Versos",
    Editor: "",
    Category: "Folk Art ",
    YearOfPublished: "1998",
    isPdf: 0,
  },
  {
    SlNo: 687,
    BookId: 706,
    BookName: "The Thames and Hudson Manual of Dyes and fabrics",
    BookImg: "book-large.jpg",
    Author: "Joyce Storey",
    Editor: "",
    Category: "Folk Art ",
    YearOfPublished: "1992",
    isPdf: 0,
  },
  {
    SlNo: 689,
    BookId: 708,
    BookName: "লোকশিল্প প্রবন্ধ",
    BookImg: "79c4e44e-8212-4025-ae16-7e33e186ae2b-image00002.jpg",
    Author: "-",
    Editor: "-",
    Category: "লোকশিল্প-বাংলাদেশ",
    YearOfPublished: "2010",
    isPdf: 1,
  },
  {
    SlNo: 691,
    BookId: 710,
    BookName: "The A-Z of Handicrafts",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "",
    Category: "Folk Art ",
    YearOfPublished: "1976",
    isPdf: 0,
  },
  {
    SlNo: 694,
    BookId: 713,
    BookName: "The Applique Quilt ",
    BookImg: "book-large.jpg",
    Author: "Dinah Travis",
    Editor: "",
    Category: "Folk Art ",
    YearOfPublished: "",
    isPdf: 0,
  },
  {
    SlNo: 695,
    BookId: 714,
    BookName: "আলোকচিত্রে সেকালের ঢাকা",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "",
    Category: "ফটোগ্রাফী",
    YearOfPublished: "2012",
    isPdf: 0,
  },
  {
    SlNo: 721,
    BookId: 740,
    BookName:
      "Festive Folding: Decorative Origami for Parties and Celebrations",
    BookImg: "book-large.jpg",
    Author: "Paul Jackson",
    Editor: "-",
    Category: "Arts and Crafts",
    YearOfPublished: "1991",
    isPdf: 0,
  },
  {
    SlNo: 779,
    BookId: 799,
    BookName: "TEXTILES ",
    BookImg: "book-large.jpg",
    Author: "RUSTAM J. MEHTA",
    Editor: "",
    Category: "Arts and Crafts",
    YearOfPublished: "",
    isPdf: 0,
  },
  {
    SlNo: 781,
    BookId: 801,
    BookName: "NATURE CRAFTS",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "",
    Category: "Arts and Crafts",
    YearOfPublished: "1993",
    isPdf: 0,
  },
  {
    SlNo: 782,
    BookId: 802,
    BookName: "ORIENTAL CARPET DESIGN",
    BookImg: "book-large.jpg",
    Author: "P.R.J.FORD",
    Editor: "",
    Category: "Arts and Crafts",
    YearOfPublished: "1992",
    isPdf: 0,
  },
  {
    SlNo: 842,
    BookId: 862,
    BookName: "ভালোবাসার তামা কাঁসা পিতল Red Metals of Love",
    BookImg: "book-large.jpg",
    Author: "সাগর অনন্ত",
    Editor: "",
    Category: "কারুশিল্প ",
    YearOfPublished: "2019",
    isPdf: 0,
  },
  {
    SlNo: 844,
    BookId: 864,
    BookName: "ভালোবাসার তামা কাঁসা পিতল=Red Metals of Love ",
    BookImg: "book-large.jpg",
    Author: "সাগর অনন্ত",
    Editor: "",
    Category: "কারুশিল্প ",
    YearOfPublished: "2019",
    isPdf: 0,
  },
  {
    SlNo: 1118,
    BookId: 1142,
    BookName: "লোকশিল্প প্রবন্ধ",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "সৈয়দ মাহবুব আলম",
    Category: "লোকশিল্প প্রবন্ধ ",
    YearOfPublished: "1999",
    isPdf: 0,
  },
  {
    SlNo: 1123,
    BookId: 1148,
    BookName: "বাংলাদেশের  লোকসংস্কৃতি",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "মাহমুদ শফিক",
    Category: "লোকশিল্প-বাংলাদেশ",
    YearOfPublished: "2005",
    isPdf: 0,
  },
  {
    SlNo: 1127,
    BookId: 1152,
    BookName: "বাংলাদেশের লোকশিল্প",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: " এস কে এম শামসুল হক",
    Category: "লোকশিল্প-বাংলাদেশ",
    YearOfPublished: "1988",
    isPdf: 0,
  },
  {
    SlNo: 1162,
    BookId: 1187,
    BookName: "বাংলাদেশের  লোকসংস্কৃতি",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "মাহমুদ শফিক",
    Category: "লোক সংস্কৃতি",
    YearOfPublished: "2005",
    isPdf: 0,
  },
  {
    SlNo: 1215,
    BookId: 1240,
    BookName: "লোক ও কারুশিল্প পত্রিকা  ",
    BookImg: "book-large.jpg",
    Author: "বাংলাদেশ লোক ও কারুশিল্প ফাউন্ডেশন",
    Editor: "-",
    Category: "পত্রিকা",
    YearOfPublished: "2022",
    isPdf: 0,
  },
  {
    SlNo: 1422,
    BookId: 1447,
    BookName: "লোক সংস্কৃতি",
    BookImg: "book-large.jpg",
    Author: "মাহমুদ শফিক",
    Editor: "-",
    Category: "লোক সংস্কৃতি",
    YearOfPublished: "2005",
    isPdf: 0,
  },
  {
    SlNo: 1621,
    BookId: 1647,
    BookName: "বাংলাদেশের লোকশিল্প ",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "সৈয়দ মাহমুদূল হাসান",
    Category: "লোকশিল্প-বাংলাদেশ",
    YearOfPublished: "1983",
    isPdf: 0,
  },
  {
    SlNo: 2114,
    BookId: 2147,
    BookName: "কবিতাসমগ্র",
    BookImg: "book-large.jpg",
    Author: "মুশাররাফ করিম",
    Editor: "",
    Category: "বাংলা কবিতা",
    YearOfPublished: "2003",
    isPdf: 0,
  },
  {
    SlNo: 2504,
    BookId: 2537,
    BookName: "বার্ষিক প্রতিবেদন ২০২০-২৯২১",
    BookImg: "book-large.jpg",
    Author: "বাংলাদেশ লোক ও কারুশিল্প ফাউন্ডেশন",
    Editor: "",
    Category: "প্রতিবেদন ",
    YearOfPublished: "2001",
    isPdf: 0,
  },
  {
    SlNo: 2505,
    BookId: 2538,
    BookName: "বার্ষিক প্রতিবেদন ২০১৮-২০১৯",
    BookImg: "book-large.jpg",
    Author: "বাংলাদেশ লোক ও কারুশিল্প ফাউন্ডেশন",
    Editor: "",
    Category: "প্রতিবেদন ",
    YearOfPublished: "2019",
    isPdf: 0,
  },
  {
    SlNo: 2506,
    BookId: 2539,
    BookName: "বার্ষিক প্রতিবেদন ২০১৮-২০১৯",
    BookImg: "book-large.jpg",
    Author: "-",
    Editor: "আহমেদ উল্লাহ",
    Category: "প্রতিবেদন ",
    YearOfPublished: "2019",
    isPdf: 0,
  },
  {
    SlNo: 2507,
    BookId: 2541,
    BookName: "লোক ও কারুশিল্প পত্রিকা",
    BookImg: "book-large.jpg",
    Author: "বাংলাদেশ লোক ও কারুশিল্প ফাউন্ডেশন",
    Editor: "-",
    Category: "পত্রিকা",
    YearOfPublished: "2022",
    isPdf: 0,
  },
  {
    SlNo: 2508,
    BookId: 2544,
    BookName: "লোক ও কারুশিল্প পত্রিকা",
    BookImg: "book-large.jpg",
    Author: "বাংলাদেশ লোক ও কারুশিল্প ফাউন্ডেশন",
    Editor: "",
    Category: "পত্রিকা",
    YearOfPublished: "2021",
    isPdf: 0,
  },
  {
    SlNo: 2509,
    BookId: 2545,
    BookName: "লোক ও কারুশিল্প পত্রিকা  ",
    BookImg: "book-large.jpg",
    Author: "বাংলাদেশ লোক ও কারুশিল্প ফাউন্ডেশন",
    Editor: "-",
    Category: "পত্রিকা",
    YearOfPublished: "2021",
    isPdf: 0,
  },
  {
    SlNo: 2510,
    BookId: 2546,
    BookName: "লোক ও কারুশিল্প পত্রিকা",
    BookImg: "book-large.jpg",
    Author: "বাংলাদেশ লোক ও কারুশিল্প ফাউন্ডেশন",
    Editor: "",
    Category: "পত্রিকা",
    YearOfPublished: "2021",
    isPdf: 0,
  },
  {
    SlNo: 2511,
    BookId: 2549,
    BookName: "লোক ও কারুশিল্প পত্রিকা  ",
    BookImg: "book-large.jpg",
    Author: "বাংলাদেশ লোক ও কারুশিল্প ফাউন্ডেশন",
    Editor: "-",
    Category: "পত্রিকা",
    YearOfPublished: "2022",
    isPdf: 0,
  },
  {
    SlNo: 2512,
    BookId: 2550,
    BookName: "লোক ও কারুশিল্প পত্রিকা  ",
    BookImg: "book-large.jpg",
    Author: "-",
    Editor: "আহমেদ উল্লাহ",
    Category: "পত্রিকা",
    YearOfPublished: "2022",
    isPdf: 0,
  },
  {
    SlNo: 2526,
    BookId: 2566,
    BookName: "লোক ও কারুশিল্প পত্রিকা ",
    BookImg: "book-large.jpg",
    Author: "বাংলাদেশ লোক ও কারুশিল্প ফাউন্ডেশন",
    Editor: "ড. আহমেদ উল্লাহ ",
    Category: "পত্রিকা",
    YearOfPublished: "2021",
    isPdf: 0,
  },
  {
    SlNo: 2987,
    BookId: 3027,
    BookName: "বাংলাদেশের লোকশিল্প",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "সৈয়দ মাহমুদূল হাসান",
    Category: "লোকশিল্প-বাংলাদেশ",
    YearOfPublished: "1995",
    isPdf: 0,
  },
  {
    SlNo: 2990,
    BookId: 3030,
    BookName: "ঐতিহ্য",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "শেখ আলাউদ্দিন",
    Category: "লোক সংস্কৃতি",
    YearOfPublished: "2008",
    isPdf: 0,
  },
  {
    SlNo: 4001,
    BookId: 4047,
    BookName: "উপন্যাসসমগ্র",
    BookImg: "book-large.jpg",
    Author: "নাজমা জেসমিন চৌধুরী ",
    Editor: "-",
    Category: "বাংলা উপন্যাস",
    YearOfPublished: "2001",
    isPdf: 0,
  },
  {
    SlNo: 4345,
    BookId: 4391,
    BookName: "লোককবিতায় বঙ্গবন্ধু",
    BookImg: "book-large.jpg",
    Author: "রবীন্দ্র গোপ",
    Editor: "",
    Category: "জীবনী",
    YearOfPublished: "2018",
    isPdf: 0,
  },
  {
    SlNo: 4463,
    BookId: 4509,
    BookName: "ঐতিহাসিক সোনারগাঁ",
    BookImg: "book-large.jpg",
    Author: "একেএম মুজ্জাম্মিল হক",
    Editor: "-",
    Category: "প্রত্নতত্ত্ব-বাংলাদেশ",
    YearOfPublished: "2016",
    isPdf: 0,
  },
  {
    SlNo: 4615,
    BookId: 4661,
    BookName: "Historic  Sonargaon ",
    BookImg: "book-large.jpg",
    Author: "-",
    Editor: "Shaficul Ameen ",
    Category: "History Sonargaon ",
    YearOfPublished: "1987",
    isPdf: 0,
  },
  {
    SlNo: 4616,
    BookId: 4662,
    BookName: "Bangladesh folk Art and crafts Foundation ",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "K. M. Habib Ullah ",
    Category: "History",
    YearOfPublished: "1998",
    isPdf: 0,
  },
  {
    SlNo: 4617,
    BookId: 4663,
    BookName: "Bangladesh folk Art and crafts Foundation ",
    BookImg: "book-large.jpg",
    Author: "-",
    Editor: "K. M. Habib Ullah ",
    Category: "History",
    YearOfPublished: "1998",
    isPdf: 0,
  },
  {
    SlNo: 4618,
    BookId: 4664,
    BookName: "Bangladesh folk Art and crafts Foundation ",
    BookImg: "book-large.jpg",
    Author: "-",
    Editor: "K. M. Habib Ullah ",
    Category: "History",
    YearOfPublished: "1998",
    isPdf: 0,
  },
  {
    SlNo: 4619,
    BookId: 4665,
    BookName: "Bangladesh folk Art and crafts Foundation ",
    BookImg: "book-large.jpg",
    Author: "-",
    Editor: "K. M. Habib Ullah ",
    Category: "History",
    YearOfPublished: "1998",
    isPdf: 0,
  },
  {
    SlNo: 4620,
    BookId: 4666,
    BookName: "Bangladesh folk Art and crafts Foundation ",
    BookImg: "book-large.jpg",
    Author: "-",
    Editor: "K. M. Habib Ullah ",
    Category: "History",
    YearOfPublished: "1998",
    isPdf: 0,
  },
  {
    SlNo: 4621,
    BookId: 4667,
    BookName: "Bangladesh folk Art and crafts Foundation ",
    BookImg: "book-large.jpg",
    Author: "-",
    Editor: "K. M. Habib Ullah ",
    Category: "History",
    YearOfPublished: "1998",
    isPdf: 0,
  },
  {
    SlNo: 4622,
    BookId: 4668,
    BookName: "Bangladesh folk Art and crafts Foundation ",
    BookImg: "book-large.jpg",
    Author: "-",
    Editor: "K. M. Habib Ullah ",
    Category: "History",
    YearOfPublished: "1998",
    isPdf: 0,
  },
  {
    SlNo: 4623,
    BookId: 4669,
    BookName: "Bangladesh folk Art and crafts Foundation ",
    BookImg: "book-large.jpg",
    Author: "-",
    Editor: "K. M. Habib Ullah ",
    Category: "History",
    YearOfPublished: "1998",
    isPdf: 0,
  },
  {
    SlNo: 5935,
    BookId: 5983,
    BookName: "Bangladesh folk Art and crafts Foundation ",
    BookImg: "book-large.jpg",
    Author: "-",
    Editor: "Shafiqul Ameen",
    Category: "History",
    YearOfPublished: "1979",
    isPdf: 0,
  },
  {
    SlNo: 5936,
    BookId: 5984,
    BookName: "Bangladesh folk Art and crafts Foundation ",
    BookImg: "book-large.jpg",
    Author: "-",
    Editor: "K. M. Habib Ullah ",
    Category: "History",
    YearOfPublished: "1998",
    isPdf: 0,
  },
  {
    SlNo: 6130,
    BookId: 6178,
    BookName: "বাংলাদেশের ঐতিহ্যবাহী বাদ্যযন্ত্র",
    BookImg: "book-large.jpg",
    Author: "সাইমন জাকারিয়া",
    Editor: "নাজমীন মর্তুজা",
    Category: "কারুশিল্প ",
    YearOfPublished: "2013",
    isPdf: 0,
  },
  {
    SlNo: 6239,
    BookId: 6287,
    BookName: "লোকশিল্পের নির্বাচিত প্রবন্ধ",
    BookImg: "book-large.jpg",
    Author: "",
    Editor: "রবীন্দ্র গোপ",
    Category: "লোকশিল্প",
    YearOfPublished: "2010",
    isPdf: 0,
  },
];
